defmodule UtilsTest do
  alias Iris.Utils

  use ExUnit.Case

  @names [
    "-normalize_call_instructions/1-fun-4-",
    "-get_call_instructions/1-fun-1-",
    "-filter_recursive_calls/1-inlined-0-",
    "-inlined-__info__/1-",
    "-__struct__/1-fun-0-",
    "-__struct__/1-inlined-0-",
    "-umbrella_compile_paths/0-fun-0-"
  ]

  @extracted [
    {"normalize_call_instructions", "1"},
    {"get_call_instructions", "1"},
    {"filter_recursive_calls", "1"},
    {"__info__", "1"},
    {"__struct__", "1"},
    {"__struct__", "1"},
    {"umbrella_compile_paths", "0"}
  ]

  test "matches an auto-generated name" do
    @names
    |> Enum.each(fn name ->
      assert Utils.is_name_not_autogenerated?(name) == false
    end)
  end

  test "extracts the correct name from an autogenerated name" do
    Enum.zip(@names, @extracted)
    |> Enum.each(fn {name, {extracted_name, arity}} ->
      assert Utils.extract_name_from_auto_generated(name, arity) == {extracted_name, arity}
    end)
  end
end
