defmodule Iris.Functions do
  @moduledoc """
    This module houses functions that work with functions extracted from a module's .beam files.
  """
  alias Iris.Entity
  alias Iris.Entity.Module.Method

  import Iris.{Utils, Calls}

  use IrisDoc

  @doc ~S"""
    Builds a list of %Method{} from compiled_code extracted from beam binary
  """
  def build_functions(compiled_code, mod_name_str) do
    compiled_code
    |> Enum.map(fn {type, name, arity, _label, code} ->
      %Method{
        name: Atom.to_string(name),
        arity: Integer.to_string(arity),
        module: mod_name_str,
        type: Atom.to_string(type),
        compiled_code: code,
        call_instructions: code |> get_call_instructions()
      }
    end)
    |> Enum.map(&indicate_macro(&1))
  end


  @idoc ~S"""
    Macros extracted from compiled .beam files all start with the prefix "MACRO-".
    Pattern match on the prefix to indicate the function is a macro and render accordingly.
  """
  defp indicate_macro(%Method{} = function) do
    case Regex.match?(~r/^MACRO-/, function.name) do
      true -> %{function | is_macro: true, name: String.trim_leading(function.name, "MACRO-") }
      false -> function
    end
  end

  @doc ~S"""
   Condense auto generated inlined, intermediate functions into the actual one
   expects method list with each item being %Method{} struct
  """
  def condense_functions(functions) do
    # turns list into map
    functions =
      functions
      |> Enum.reduce(%{}, fn function, acc ->
        {name, arity} = {function.name, function.arity}
        {name, arity} = extract_name_from_auto_generated(name, arity)

        # append call instructions if already found one method (auto generated or actual) with same name
        if Map.has_key?(acc, {name, arity}) do
          %Method{} = actual_fn = Map.get(acc, {name, arity})

          actual_fn = %{
            actual_fn
            | call_instructions: actual_fn.call_instructions ++ function.call_instructions
          }

          # return new acc with updated function
          Map.put(acc, {name, arity}, actual_fn)
        else
          # put function in acc with {name, arity} as key
          Map.put(acc, {name, arity}, function)
        end
      end)

    # reverts map into list
    functions = Map.values(functions)

    functions
  end

  @doc ~S"""
   Filters auto generated function.
   these functions are condensed into actual defined ones in [condense_functions/2]
   and are no longer required to be part of [functions] list
  """
  def filter_auto_generated(functions) do
    functions
    |> Enum.filter(&is_name_not_autogenerated?(&1.name))
  end

  @doc ~S"""
    Sort based on the criteria EXP > INT
  """
  def sort_functions(functions) do
    functions
    |> Enum.sort(fn ma, mb ->
      case {ma.html_type_text, mb.html_type_text} do
        {"EXP", "INT"} -> true
        _ -> false
      end
    end)
  end

  def flatten_all_functions(apps) do
    Enum.reduce(apps, [], fn app, acc ->
      Entity.Application.get_all_functions(app) ++ acc
    end)
  end

  @doc ~S"""
    Set docs field for function if doc exists.
    Doc can be fetched from either @doc or @idoc
  """
  def set_function_docs(%Method{} = method, %{} = method_docs) do
    key = method.name <> "/" <> method.arity

    case Map.get(method_docs, key, nil) do
      nil -> method
      doc -> %{method | ex_doc: doc}
    end

    with doc <- Map.get(method_docs, key, nil),
         false <- is_nil(doc),
         false <- doc.source_doc == :none do
      %{method | ex_doc: doc}
    else
      _ -> method
    end
  end
end
