defmodule Iris.Utils do
  @moduledoc """
    Utility functions used by multiple modules.
  """

  @doc ~S"""
    All functions that do not match the regex.
    This is the same regex used in [extract_name_from_auto_generated/2]
  """
  def is_name_not_autogenerated?(name) do
    !(Regex.match?(~r/^-inlined(.*)-$/, name) ||
        Regex.match?(~r/^-(.*)-(fun|inlined)-(.*)-$/, name))
  end

  @doc ~S"""
   returns {name, arity} from auto generated methods
   "-inlined-__help__/1-" --> {"__help__", 1}
   "-build_applications/1-(fun|inlined)-1-" --> {"build_applications", 1}
  """
  def extract_name_from_auto_generated(name, arity) do
    cond do
      # anchors ^ and $ for precision matching
      Regex.match?(~r/^-inlined(.*)-$/, name) ->
        %{"name" => name, "arity" => arity} =
          Regex.named_captures(~r/(-inlined-)(?<name>.*)\/(?<arity>.*)-/, name)

        {name, arity}

      Regex.match?(~r/^-(.*)-(fun|inlined)-(.*)-$/, name) ->
        %{"name" => name, "arity" => arity} =
          Regex.named_captures(~r/^(-)(?<name>.*)\/(?<arity>.*)-(fun|inlined)-(.*)-/, name)

        {name, arity}

      true ->
        {name, arity}
    end
  end

  @doc ~S"""
    Used for logging if verbose flag is passed when mix iris is invoked.
    Violates macro hygiene and fetches `config` from user context with the var!() macro,
    checks if verbose flag is set, and logs if set, else does nothing.
  """
  defmacro log_verbose(do: block) do
    quote do
      if var!(config).verbose do
        unquote(block)
      end
    end
  end
end
