import { useGlobalState, useGlobalDispatch } from "../ctx/globalContext.jsx";
import { Card } from "flowbite-react";
import Markdown from "react-markdown";
import {
  getDocumentation,
  getDocumentationCardHeader,
} from "../helpers/stateHelper.js";
import { Heading } from "./ui/heading.jsx";
import { Toggle } from "./ui/toggle.jsx";
import { Badge } from "./ui/badge.jsx";

export function Documentation({}) {
  const state = useGlobalState();
  const dispatch = useGlobalDispatch();

  const docsType = state.docsType;
  const docsEntity = state.docsEntity;
  const docMarkdown = getDocumentation(docsType, docsEntity);
  const showDocumentation = state.showDocumentation;
  const attributionComponent = get_attribution_component(docsType, docsEntity);

  const toggle = () => {
    dispatch({
      type: "toggleDocumentationDisplay",
      keepDisplaying: false, // a hack to switch off the display when pressed again, instead of re-rendering the content.
    });
  };

  const headerText = getDocumentationCardHeader(docsType, docsEntity);

  if (showDocumentation) {
    return (
      <Card className="doc-card">
        <div className="doc-card-header">
          <Heading level={3}>{headerText}</Heading>
          {get_close_button(toggle)}
        </div>
        <div className="markdown content-inner">
          <Markdown>{docMarkdown}</Markdown>
          {attributionComponent}
        </div>
      </Card>
    );
  }
  return <></>;
}

function get_close_button(onClick) {
  return (
    <Badge onClick={onClick} className="cursor-pointer" isCircle={false} intent={"danger"}>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        strokeWidth={1.5}
        stroke="currentColor"
        className="size-6"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
        />
      </svg>
    </Badge>
  );
}

function get_attribution_component(docsType, docsEntity) {
  switch (docsType) {
    case "module":
      return ex_doc_attribution();
    case "method": {
      if (docsEntity.html_type_text == "EXP") return ex_doc_attribution();
      return iris_doc_attribution();
    }
  }
}

function ex_doc_attribution() {
  return (
    <div className="attribution-container flex flex-row items-center text-sm mt-5">
      <div className="mr-1">Documentation generated by</div>
      <a
        target="_blank"
        href="https://github.com/elixir-lang/ex_doc"
        className=""
      >
        ExDoc
      </a>
    </div>
  );
}

function iris_doc_attribution() {
  return (
    <div className="attribution-container flex flex-row items-center text-sm mt-5">
      <div className="mr-1">Documentation generated by Iris </div>
      <a
        target="_blank"
        href="https://github.com/rahultumpala/iris"
        className=""
      >
        @idoc
      </a>
    </div>
  );
}
